### PR TITLE
Optional alternate stream

### PR DESCRIPTION
**Pull request by snoopyjoe**
Added optional bool setting to use the "video_alt" url with inputstream adaptive. LibreElec and inputstream 2.2.8 still doesn't like the video switching Sony does. But my OSX and inputstream 2.2.8 doesn't seem to have an issue with the default "video" url.

### CODE REVIEW

**Comment by eracknaphobia** [comment]
I wonder if the playback issue has to do with [this](https://developer.apple.com/library/content/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-AD_PLAYLIST__DISCONTINUITIES_)? I noticed that most (if not all the time) the main stream has "_ads" tacked on to it where the alternate does not. I wonder if it would be better to search for that in the stream url and use the alternate if found?

**Comment by snoopyjoe** [comment]
I noticed that difference too. That post does seem to describe the issues I see on my end. A stream will be playing fine, but once a commercial starts the stream fails. Trying to load the stream again also fails. But once the commercial is over, the stream has no issues. I'll ask the forum to test the video_alt url and post their results. Someone said before that url had a lower resolution. If the alt url works best for everyone then we can use that url when it's available.

**Comment by DiR3Wolf** [comment]
@snoopyjoe I see Eracknaphobia is already using video_alt as default when inputstream in enabled. I previously wrote in the forums that resolution were lower when using video_alt. That was because inputstream wasn't able to select the "max" resolution setting. That was fixed, I believe, starting 2.2.8  (now it is 2.2.16 on lastest nightly). I don't see a need for a toggle anymore (unless it is still needed for Kodi 17?). If you agree, let's close this pull request.

**Comment by snoopyjoe** [comment]
Thanks for pointing that out @DiR3Wolf. Somehow my fork's psvue.py file didn't get updated after the last commit. A lot of people on v17 still use an old(but stable) version of Inputstream. My v17.6 boot hasn't had any issues when using video_alt. Ill close this request.

**Pull request closed without merging**
