### PR TITLE
VideoPlayer and Menu organization

### PR DESCRIPTION
**Pull request by snoopyjoe**
Update VideoPlayer info display with a "Live" or "On Demand" badge.
LiveTV and TImeline section displays whether show is Live or the date and time it will be available.

### CODE REVIEW

**Review by eracknaphobia — APPROVED** [review]
Great work!

**Comment by eracknaphobia** [comment]
I think it's time I update the version in my repo to include these changes. Could you post a short list of changes you've made since version 2017.11.3? I don't want to miss anything.

**Comment by snoopyjoe** [comment]
Yeah no problem.

**Comment by snoopyjoe** [comment]
Timeline section now available with episode availability detail

Fix add/remove show and channel ability

Watched live or on demand shows available in Recently Watched

VideoPlayer display info updated 

LiveTV menu updated with live show info

**Pull request merged**
