### PR TITLE
Display and stream updates

### PR DESCRIPTION
**Pull request by snoopyjoe**
+Prioritize VOD stream over DVR stream for episode
+Change My Shows label to My DVR to stay current with Sony labeling
+Replace broadcast date with airing date for betting sorting
+Add "NEW" tag to new episodes

### CODE REVIEW

**Comment by DiR3Wolf** [comment]
Hey Snoop. Great work! BTW, do you know how to display the show/movie title for the ALL Channels directory (to display similar to the TV menu's recent channel). Under that ALL channels directory, there is only Title=channel name, and plot. But you can't see what movie/show is playing, other than guessing by the plot. Of course, there is EPG guide, but I thought it would be a nice option. Let me know.

**Comment by snoopyjoe** [comment]
@DiR3Wolf after looking at the json, the show info is there. Though the best I could do is add the show title to the plot to be displayed and capitalize it. So under the default skin view type list you get on the **left**: 
channel name
SHOW TITLE +  plot
**middle**:
channel name
**right**:
icon

In the player you get the channel name, genre, icon, show title + plot. This is displayed from top to bottom.

I'm not sure why setInfo does not set the 'original_title' does not display even in the default skin.
[Pictures](https://imgur.com/a/0rnuhKa)

**Comment by DiR3Wolf** [comment]
@snoopyjoe Great, thanks!!! I didn't know how to pull the info from json. I will try this later. Alternative, you can use "show_title" as follows:

`
'title': title,`
`'TVShowTitle' : show_title, #this will display the show's title wherever the label TVShowTitle is used in the skin.`

I don't think the skin uses the orgininaltitle label. At least not on the skins I have worked on. Depending on if it is used on Estuary, you may not need it to append to the plot.

**Comment by snoopyjoe** [comment]
@DiR3Wolf I posted the code to my testing branch if you want look at it. I'll try using TVShowTitle instead originaltitle.

**Comment by DiR3Wolf** [comment]
@snoopyjoe I tested it last night. Don't replace original title info label, it does work on some skins info (I was wrong). Just add the label for TV shows as above. I will dig in to default skin labels to see what works best. I think your idea to add it to the plot is genius. Great work as usual!!!

**Comment by snoopyjoe** [comment]
I added the ability to add a show to the Kodi library. Having the VOD stream prioritize over the DVR stream made this more useable. The library folder will update when "My DVR" is opened 8hrs since last update. There are a couple shows that export jibberish show titles, but this has to be a Sony issue because even utf8 doesn't fix it.

**Pull request merged**
