### PR TITLE
Prefer DVR over VOD

### PR DESCRIPTION
**Pull request by hackthis02**
Closed caption doesn't seem to work with VOD feeds. This prefers DVR feeds when both are available.

### CODE REVIEW

**Comment by snoopyjoe** [comment]
It would be great if we can get the add-on to give a choice of DVR or VOD when opening an episode. This is how the website does it. I tried adding this many months ago because when a DVR episode had playback issues or cut a recording there was no way to choose the VOD option.

**Comment by hackthis02** [comment]
I thought about that too. It is possible, but I'm not as familiar with Kodi's menu system as I'd like to be. I can start looking into this unless you kept your earlier attempt.

**Comment by snoopyjoe** [comment]
I don't have the code I was working on but I believe you may need to make a new function that the list episodes function calls. I'll start working on this again as my Xcode finally updated.

**Comment by snoopyjoe** [comment]
I got the DVR or VOD selection code working on my [Testing](https://github.com/snoopyjoe/plugin.video.psvue/tree/testing) branch. Let me know how that works on your end. I added a 10 second "autoclose" for those who let the videos play back to back without any user commands.

**Comment by hackthis02** [comment]
Love it. I changed one thing to match closer to the wording of the website. 
main.py:120: 
`choice = xbmcgui.Dialog().yesno("Choose your preference","Where would you like to watch this episode?", nolabel='ON DEMAND', yeslabel='DVR', autoclose=10000)`

But if this works for you and @eracknaphobia then I'll close this PR and we can do with that idea.

**Comment by snoopyjoe** [comment]
I got the wording from the Android app, but thats better. Looks good.

**Pull request closed without merging**
