### PR TITLE
Reworked badges for show/episode listings

### PR DESCRIPTION
**Pull request by hackthis02**
I reworked the badges for shows/episodes to show if it is a DVR or VOD. Moved the New badge to the front so it's easier to find if the show is also heavily syndicated. Removed the aired date since it's already being displayed else where on the screen. This is simply a few personal suggestions to make the menus a little easier to manage. Hopefully you agree.

### CODE REVIEW

**Comment by snoopyjoe** [comment]
Do you have a picture of the badges? I assume this will show mainly in the My DVR section. Sounds really cool and similar to the psvue website.

**Comment by hackthis02** [comment]
That's kind of what I was going for. With the current layout, I would have to take out my phone to see the name of the more recent episode. Now I can just scroll to ones with New in front. It also works in the other listings. I'm simply scanning for the badge var that Sony sends us. [Demos](https://imgur.com/a/BucUl4k)

**Comment by eracknaphobia** [comment]
Great work, thanks!

**Comment by snoopyjoe** [comment]
Awesome! Under next airings does the time each show airs not fit? From the pictures I would say that's the only thing that would top it off.

**Comment by hackthis02** [comment]
I can look into that. I just assumed it was only displaying the very next show on each of the channels.

**Comment by snoopyjoe** [comment]
It would display both the show and at what hour it starts. It's no big deal actually since most people use Kodi18 and the EPG. Those still on 17.6 probably still use next airings.

**Comment by hackthis02** [comment]
The two other things I wanted to point out was, in the My DVR view, any shows with "new" episodes get brought to top of the list.  The other thing I wanted to ask about was if we removed

`json_source = sorted(json_source, key=lambda k: k['airing_date'], reverse=True)`

from `list_episodes` It would give the same sorting as the app/website.

**Comment by eracknaphobia** [comment]
I'm fine with that as long as @snoopyjoe doesn't have any objections.

**Comment by snoopyjoe** [comment]
No issues here. Anything that makes it closer reassemble the website is good to me.
On my test branch I added the hour a show will air in the future. In next airings it looks fine but in My DVR the future episode is always the top episode.

**Comment by hackthis02** [comment]
That makes sense since it first episode in the app too. The odd thing I saw was PSV doesn't send it as a new episode. So I'm not sure yet how to tell if it's the latest or just a rerun.

**Comment by eracknaphobia** [comment]
So we all good here? I noticed that the official kodi version is woefully behind (2018.3.24) and wanted to make sure this change got finalized before sending it off. @hackthis02  Do you want to make a PR to remove the json source sorting?

**Comment by hackthis02** [comment]
Yeah, just added it. [#35](https://github.com/eracknaphobia/plugin.video.psvue/pull/35). I also have a PR on your simpsons world repo.

**Comment by eracknaphobia** [comment]
Ok, I'll take a look.

**Pull request merged**
